***REFERENCES:***
* https://pytorch.org/docs/stable/tensors.html
*  https://www.youtube.com/watch?v=Z_ikDlimN6A&t=73s

In [2]:
import torch
torch.__version__

'1.13.0+cu116'

**Tensors represent data in a numerical way.**

---


the tensor would have three dimensions, one for colour_channels, height and width.
 [colour_channels, height, width]

Whenever we use Pytorch we have to transform data to tensors.

**Create different types of tensors:**



> scalar is a single number, it's of type torch.Tensor.



In [3]:
# 1ST TYPE: scalar()
scalar = torch.tensor(20)
scalar


tensor(20)

In [4]:
scalar.type()

'torch.LongTensor'

In [5]:
scalar.ndim

0

In [6]:
scalar.shape

torch.Size([])

In [7]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

20

**A vector is a single dimension tensor but can contain many numbers.**

In [8]:
# 2nd type: Vector()
vector = torch.tensor([20,10,30])
vector

tensor([20, 10, 30])

In [9]:
# Check the number of dimensions of vector
vector.ndim


1

The number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([).

In [10]:
# Check shape of vector
vector.shape

torch.Size([3])

Because it contains 3 element.

**MATRIX has two dimensions**

In [11]:
#3rd type: MATRIX()

MATRIX = torch.tensor([[20, 9], 
                       [5, 17]])
MATRIX

tensor([[20,  9],
        [ 5, 17]])

In [12]:
# Check number of dimensions
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

Note: 

1.   Tensor can be scalar or Matrix or Vector.
2.   Tensor can contain million of elements and to know the dimension just count how many square bracket or use the function: x.ndim. Tensor can be of n dimension.



In [14]:
TENSOR = torch.tensor([[[16, 23, 43],
                        [3, 5, 79],
                        [1, 7, 8],
                        [7, 65, 35]]])
TENSOR

tensor([[[16, 23, 43],
         [ 3,  5, 79],
         [ 1,  7,  8],
         [ 7, 65, 35]]])

In [15]:
TENSOR.ndim
#([[[== 3 square bracket

3

In [16]:
TENSOR.shape

torch.Size([1, 4, 3])

**Random Tensor**

In [17]:
# Create a random tensor of size (3,224, 224)
#random tensor in the common image shape of [3,224, 224] ([color_channels,height, width])
randomTensor_image_size = torch.rand(size=(3,224, 224))
randomTensor_image_size.shape


torch.Size([3, 224, 224])

In [18]:
randomTensor_image_size

tensor([[[0.6908, 0.0948, 0.4405,  ..., 0.7476, 0.7407, 0.8593],
         [0.3423, 0.5680, 0.6197,  ..., 0.1313, 0.9550, 0.2276],
         [0.4312, 0.4067, 0.9143,  ..., 0.8965, 0.4876, 0.3918],
         ...,
         [0.1814, 0.8973, 0.2163,  ..., 0.9625, 0.3806, 0.8965],
         [0.9859, 0.6149, 0.8981,  ..., 0.8328, 0.8494, 0.6158],
         [0.0205, 0.8073, 0.0371,  ..., 0.5563, 0.3387, 0.2999]],

        [[0.1912, 0.6265, 0.9352,  ..., 0.1523, 0.2111, 0.7569],
         [0.3006, 0.0367, 0.2365,  ..., 0.4107, 0.0351, 0.1529],
         [0.0768, 0.1104, 0.1971,  ..., 0.4538, 0.0517, 0.7402],
         ...,
         [0.4734, 0.1833, 0.6421,  ..., 0.9678, 0.6354, 0.6597],
         [0.3546, 0.1927, 0.9163,  ..., 0.2143, 0.5657, 0.0334],
         [0.9177, 0.5564, 0.8333,  ..., 0.5703, 0.7532, 0.8519]],

        [[0.5405, 0.0096, 0.0106,  ..., 0.5807, 0.9451, 0.0109],
         [0.4745, 0.1677, 0.6304,  ..., 0.1059, 0.0812, 0.9104],
         [0.9268, 0.9508, 0.1982,  ..., 0.3496, 0.4896, 0.

In [19]:
randomTensor_image_size.ndim

3

**Zeros and ones tensor**


Useful when we ant to use mask: masking some of the values in one tensor with zeros to make a model know that it should not learn them.



In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(2, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(size=(2, 3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
#example of masking:
zeros_F_col=torch.zeros(4,1)
zeros_F_col

tensor([[0.],
        [0.],
        [0.],
        [0.]])

In [24]:
TENSOR

tensor([[[16, 23, 43],
         [ 3,  5, 79],
         [ 1,  7,  8],
         [ 7, 65, 35]]])

In [25]:
maskingF_col=zeros_F_col*TENSOR
maskingF_col

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

**Range and zeros_like**

In [26]:
# Create a range of values 0 to 10
tensor_arange = torch.arange(start=0, end=10, step=1)
tensor_arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# Tensor of zeros similar to another tensor
#similar means will have same shape
tensor_zeros = torch.zeros_like(input=tensor_arange)
tensor_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Pytorch data types:**




Tensor data type is one of the important error that we can get while doing operation on tensors:
* Tesors not in right data type.what datatype are the elements within the tensor stored in.
* Tensors not in right shape.what shape is the tensor? (some operations require specific shape rules).
* Tensors not in right device. what device is the tensor stored on? (usually GPU or CPU).


In [28]:
# Default datatype for tensors is float32
float32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or the datatype passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations perfromed on the tensor are recorded 

float32_tensor

tensor([3., 6., 9.])

In [29]:
 float32_tensor.dtype

torch.float32

In [30]:
float32_tensor.shape

torch.Size([3])

**Changing type of tensor**

In [31]:
float64_tensor=float32_tensor.type(torch.float64)
float64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [32]:
float16=torch.tensor( [3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None, 
                               requires_grad=False)

In [33]:
float64_tensor*float16
#Here it works without generating an error but may be in big neural network it will generate an error

tensor([ 9., 36., 81.], dtype=torch.float64)

In [34]:
float64_tensor.device,float64_tensor.shape,float64_tensor.dtype

(device(type='cpu'), torch.Size([3]), torch.float64)

**Basic operations**


In [35]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
#Addition
tensor + 5

tensor([6, 7, 8])

In [36]:
#Multiplication
tensor * 5

tensor([ 5, 10, 15])

In [37]:
# Can also use torch functions
torch.multiply(tensor, 5)

tensor([ 5, 10, 15])

Here either we use (*) or multiply function gives the same result.

**Matrix multiplication:**
* Pay attention to the shape of matrices.(x,y)*(y,z) 
* tensor * tensor will generate element wise multiplication. 
* tensor.matmul(tensor) will generate matrix multiplication.(like dot product)

In [38]:
# Element-wise matrix multiplication
tensor * tensor


tensor([1, 4, 9])

In [39]:
# Matrix multiplication
#(1*1)+(2*2)+(3*3)
#1st method:
torch.matmul(tensor, tensor)

tensor(14)

In [40]:
#2nd method:
tensor @ tensor

tensor(14)

**Solving tghe error of shape in multiplication: Transpose()**

In [46]:
# Shapes need to be in the right way  
tensor_X = torch.tensor([[14, 21],
                         [8, 7],
                         [20, 6]], dtype=torch.float32)

tensor_Y = torch.tensor([[3, 3],
                         [2, 5], 
                         [5, 6]], dtype=torch.float32)



In [47]:
print(tensor_X.shape)
print(tensor_Y.shape)

torch.Size([3, 2])
torch.Size([3, 2])


In [48]:
# We need to convert B to Transpose B to implement the multiplication
print(tensor_X.shape)
print(tensor_Y.T.shape)

torch.Size([3, 2])
torch.Size([2, 3])


In [50]:
torch.mm(tensor_X,tensor_Y.T)
#mm is a short of mutmul

tensor([[105., 133., 196.],
        [ 45.,  51.,  82.],
        [ 78.,  70., 136.]])

**Aggregation function in pytorch**
* **Note:** when we use the mean function we may have dtype error so we have to change the data type to float when we use it.

In [51]:
tensor_X_Agg= torch.tensor([[14, 21],
                         [8, 7],
                         [20, 6]])

In [52]:
torch.mean(tensor_X_Agg)

RuntimeError: ignored

In [53]:
torch.mean(tensor_X_Agg.type(torch.float32))

tensor(12.6667)

In [55]:
torch.min(tensor_X_Agg),torch.max(tensor_X_Agg),torch.sum(tensor_X_Agg)

(tensor(6), tensor(21), tensor(76))

In [57]:
tensor_X_Agg

tensor([[14, 21],
        [ 8,  7],
        [20,  6]])

In [56]:
#Argmin() Argmax() position of min value and max value
torch.argmin(tensor_X_Agg),torch.argmax(tensor_X_Agg)

(tensor(5), tensor(1))

**Manipulating tensors shape:**

* **torch.reshape(input, shape):** Reshapes input to shape (the new shape should be the same as the original).

* **torch.Tensor.view(shape):**Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

* **torch.permute(input, dims):**Returns a view of the original input with its dimensions permuted (rearranged) to dims.

* **torch.stack(tensors, dim=0):**Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

* **torch.squeeze(input):**Squeezes input to remove all the dimenions with value 1.

* **torch.unsqueeze(input, dim):**Returns input with a dimension value of 1 added at dim.

In [58]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [60]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [63]:
#view (keeps same data as original but changes view) the view share the same memory as the original.
x_view = x.view(1, 9)
x_view,x_view.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [66]:
#Stacking the tensors vertically and horizontally
x_stacked_ver = torch.stack([x, x, x], dim=0) 
x_stacked_ver

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [67]:
x_stacked_hor = torch.stack([x, x, x], dim=1) 
x_stacked_hor

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

In [74]:
#squeeze() remove all 1d element
X=torch.zeros(2,3)
X,x.shape

(tensor([[0., 0., 0.],
         [0., 0., 0.]]), torch.Size([9]))

In [75]:
X_squeeze=torch.squeeze(X)
X_squeeze,X_squeeze.shape

(tensor([[0., 0., 0.],
         [0., 0., 0.]]), torch.Size([2, 3]))

In [78]:
X_unsqueeze=torch.unsqueeze(X,dim=0)
X_unsqueeze,X_unsqueeze.shape

(tensor([[[0., 0., 0.],
          [0., 0., 0.]]]), torch.Size([1, 2, 3]))

In [79]:
# permute means rearange the order of the dimension 
x = torch.rand(size=(224, 224, 3))
x_permuted = x.permute(2, 0, 1) 
# which means: we have (index0 = 224), (index1 = 224), (index2 = 3)
#now it will (index0 = 3), (index1 = 224), (index2 = 224) so they are rearanged
x.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

Permuting returns a view shares the same data as the original, the values in the permuted tensor will be the same as the original tensor they share the same memory so any change in the view the original values can saw it and vice versa.
ex: [height, width, num of chanel] can become [num of chanel, height, width]

**Indexing in Pytorch**

* ***Note***: Similar to indexing in Numpy

In [80]:
x= torch.arange(1, 10).reshape(1, 3, 3)

In [82]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [86]:
x[0][0][0]
#0 tensor 
#0 array
#0 element

tensor(1)

In [88]:
x[0, 0, 0]


tensor(1)

In [89]:
x[0, 1, 0]

tensor(4)

In [90]:
x[0, 1, 2]

tensor(6)

In [91]:
x[:, 1, 2]

tensor([6])

In [92]:
x[:, : , 2]

tensor([[3, 6, 9]])

In [85]:
x[:1, :]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

**NumPy array -> PyTorch**
* torch.from_numpy(ndarray)

**PyTorch tensor -> NumPy array**
* torch.Tensor.numpy()

In [93]:
import numpy as np
array = np.arange(0, 10)
tensor = torch.from_numpy(array)
array, tensor

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))



---
To convert a NumPy array 
(float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), we should use tensor = torch.from_numpy(array).type(torch.float32)

***Reproducibility Concept***

In [96]:
random_seed=42 #we use it to reduce the randomness to dont make it every time we run the cells generate new values 
torch.random.manual_seed(seed=random_seed)
random_ten=torch.rand(2,3)
random_ten

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])